#!/usr/bin/env bash
#  A Script that configures a new Ubuntu machine to Perform a 301-redirection

sudo apt-grt update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html


# Performing a 301 Redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/tich123 permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restarting Nginx service
sudo service nginx restart
