#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<" | sudo tee -a /etc/haproxy/haproxy.cfg
frontend webtich.tech
    timeout client  30000
    bind 0:80
    default_backend webtich.tech_backend

backend webtich.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 230726-web-01 52.3.252.57:80 check
    server 230726-web-02 34.207.211.229:80 check

"

sudo service haproxy restart

